# Generated by Django 5.0.6 on 2024-06-05 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
